#security:
#  oauth2:
#    client:
#      clientId: 0oaf7390yzPJB6wUc0h7
#      clientSecret: x9eXRiWXDExb7zz_jIo3Z7FSv_dDrv7TqgbaWiJo
#    resource:
#      tokenInfoUri: https://dev-365880.oktapreview.com/oauth2/default/v1/introspect
#  basic:
#    enable: false
#oauth:
#  clientId: 975187888540-7bb6lo6d0mhota05nsv36tfhh695qdhi.apps.googleusercontent.com
#  clientSecret: 3cMEGDwVe_VL9PvmtWBWE3IJ
#  checkTokenUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token={accessToken}
#  userInfoUrl: https://www.googleapis.com/plus/v1/people/me

server:
  port: 8084

spring:
  datasource:
#    url: jdbc:h2:./db/test5Db;AUTO_SERVER=TRUE;MVCC=TRUE;IFEXISTS=FALSE
     url: jdbc:h2:./db/test5Db;AUTO_SERVER=TRUE;
  h2:
  console:
    enabled: true

  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        ddl-auto: create-drop
    show-sql: false

seasonLoaded: "2017"
pythonStatURL: "http://localhost:5000"

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: debug
      springframework:
        security: DEBUG
    com:
      example:
        ipl:
          iplstats: DEBUG
  pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/udaykiranss/Code/Logs/application-dev.log




